[runtime]
dlthub_telemetry = true

[normalize.data_writer]
disable_compression=true

[source.filesystem]
bucket_url="gs://dlt-demo_source-data/"
file_path="src_google_analytics/src_ga_sessions_fct.csv"

[duckdb]
db_file_path="data/data.duckdb"
source_schema="src_google_analytics"
source_table="src_ga_sessions_fct"

[dbt_repo]
repo_url="https://github.com/thedatagata/dlt_dbt_models"
package_profile="dbt_models"

[destination.filesystem]
bucket_url="gs://dlt-demo_staging-data"
schema_name="stg_google_analytics"
table_name="stg_ga_users_dim"




