[runtime]
dlthub_telemetry = true

[normalize.data_writer]
disable_compression=true

[source.filesystem]
bucket_url="gs://wt-source_data/"
file_path="google_analytics/src_sessions.csv"

[duckdb]
db_file_path="data/data_swamp.duckdb"
source_schema="raw_data"
source_table="src_sessions_fct"

[dbt_repo]
repo_url="https://github.com/thedatagata/dlt_dbt_models.git"
package_profile="dbt_models"

[destination.filesystem]
folder_name="google_analytics" 
file_name="customer_dimensions"




