[destination.filesystem]
bucket_url = "{REPLACE_WITH_DESTINATION_BUCKET_NAME}"

[credentials]
project_id = "{REPLACE_WITH_PROJECT_NAME}" 
private_key = "{REPLACE_WITH_IAM_PRIVATE_KEY}"
client_email = "{REPLACE_WITH_SERVICE_ACCOUNT_EMAIL}"